// Datos demo (se usan si no hay Supabase configurado)
export const DEMO_EVENTS = [
  { id: 'd1', sede: 'Nacional', title: 'Día de la Cocina Chilena: nuestros sabores en tu campus', category: 'Actividad', description: 'Actividades y degustación de preparaciones típicas que ponen en valor aspectos culinarios de nuestra cultura. Organiza Asuntos Estudiantiles.', date: '2026-04-13', time: '12:30', location: 'Hall central, campus Bellavista', faculty: 'Asuntos Estudiantiles', capacity: 200, requires_rsvp: true, tags: ['nacional', 'gastronomía'], status: 'published', image_url: '' },
  { id: 'd2', sede: 'Santiago', title: 'Lanzamiento Política Regional de Turismo Sostenible 2035', category: 'Lanzamiento', description: 'Presentación de la Política Regional de Turismo Sostenible 2035, RMS, que consolida una visión compartida entre el sector público, privado, la academia y la sociedad civil. Organizan Gobierno de Santiago, FENG USS y VcM.', date: '2026-04-14', time: '12:00', location: 'Bolsa de Santiago, La Bolsa 84', faculty: 'Economía, Negocios y Gobierno', capacity: 150, requires_rsvp: true, tags: ['turismo', 'política'], status: 'published', image_url: '' },
  { id: 'd3', sede: 'Santiago', title: 'Ceremonia de Titulación — Kinesiología', category: 'Ceremonia', description: 'Estudiantes de Kinesiología de la Facultad de Ciencias de la Rehabilitación y Calidad de Vida culminan su proceso curricular.', date: '2026-04-14', time: '17:00', location: 'Aula Magna, campus Bellavista', faculty: 'Kinesiología', capacity: 400, requires_rsvp: false, tags: ['titulación'], status: 'published', image_url: '' },
  { id: 'd4', sede: 'Santiago', title: 'Entrega de Manual de Conservación en el GAM', category: 'Actividad VcM', description: 'Estudiantes de Arte y Conservación del Patrimonio USS entregan un manual elaborado en el curso de Materiales Inorgánicos.', date: '2026-04-16', time: '11:00', location: 'Centro Cultural Gabriela Mistral (GAM)', faculty: 'Arte y Conservación del Patrimonio', capacity: 80, requires_rsvp: true, tags: ['patrimonio'], status: 'published', image_url: '' },
  { id: 'd5', sede: 'Santiago', title: 'Emprende Day', category: 'Conversatorio', description: 'Conversatorio con actores del ecosistema emprendedor. Incluye mentorías personalizadas "Cuéntanos tu idea".', date: '2026-04-16', time: '11:00', location: 'Sala A103, campus Ciudad Universitaria', faculty: 'Ingeniería Comercial', capacity: 120, requires_rsvp: true, tags: ['emprendimiento'], status: 'published', image_url: '' },
  { id: 'd6', sede: 'Santiago', title: 'Ceremonia de Distinción a la Excelencia Docente', category: 'Ceremonia', description: 'Reconocimiento a los académicos destacados por su compromiso, innovación y excelencia. Organiza Dirección General de Docencia.', date: '2026-04-16', time: '12:00', location: 'Aula Magna, campus Bellavista', faculty: 'Dirección General de Docencia', capacity: 400, requires_rsvp: false, tags: ['docencia'], status: 'published', image_url: '' },
  { id: 'd7', sede: 'Santiago', title: 'Feria de Bienestar y Autocuidado', category: 'Feria', description: 'Stands informativos y actividades recreativas de salud física y mental. Organiza Bienestar Estudiantil e Inclusión.', date: '2026-04-16', time: '12:00', location: 'Patio central, campus Los Leones', faculty: 'Bienestar Estudiantil', capacity: 300, requires_rsvp: false, tags: ['salud', 'bienestar'], status: 'published', image_url: '' },
  { id: 'd8', sede: 'Santiago', title: 'Clase magistral: "La voz de la Enfermera líder"', category: 'Clase magistral', description: 'Clase enfocada en el liderazgo en enfermería, a partir de la experiencia de la Dra. Paulina Bravo, reconocida entre las 100 mujeres líderes de Chile 2025.', date: '2026-04-16', time: '17:30', location: 'Auditorio, campus Los Leones', faculty: 'Enfermería', capacity: 200, requires_rsvp: true, tags: ['enfermería', 'liderazgo'], status: 'published', image_url: '' },
  { id: 'd9', sede: 'Santiago', title: 'Taller de Liderazgo y Trabajo en Equipo', category: 'Taller', description: 'Instancia formativa orientada al desarrollo de competencias para el trabajo colaborativo.', date: '2026-04-17', time: '16:30', location: 'Sala E 205, campus Los Leones', faculty: 'Escuela de Liderazgo', capacity: 40, requires_rsvp: true, tags: ['liderazgo'], status: 'published', image_url: '' },
  { id: 'd10', sede: 'Santiago', title: 'Running Talks — Recta final Maratón de Santiago', category: 'Seminario', description: 'Expertos y deportistas entregan consejos en nutrición, preparación y motivación. Organizan Licenciatura en Ciencias de la Actividad Física y VcM.', date: '2026-04-17', time: '18:00', location: 'Aula Magna, campus Bellavista', faculty: 'Ciencias de la Actividad Física', capacity: 400, requires_rsvp: true, tags: ['deporte', 'maratón'], status: 'published', image_url: '' },
  { id: 'd11', sede: 'Concepción', title: 'Conmemoración Mes del Libro', category: 'Exposición', description: 'Exposición y venta de ejemplares en el marco del Mes del Libro. Organiza Red de Bibliotecas.', date: '2026-04-13', time: '09:00', location: 'Hall Biblioteca, campus Las Tres Pascualas', faculty: 'Red de Bibliotecas', capacity: null, requires_rsvp: false, tags: ['libro'], status: 'published', image_url: '' },
  { id: 'd12', sede: 'Concepción', title: 'Olimpiadas Especiales 2026', category: 'Actividad VcM', description: 'Pedagogía en Educación Diferencial participa en la jornada deportiva orientada a promover la inclusión.', date: '2026-04-14', time: '09:00', location: 'Estadio Ester Roa Rebolledo, Concepción', faculty: 'Educación Diferencial', capacity: null, requires_rsvp: false, tags: ['inclusión', 'deporte'], status: 'published', image_url: '' },
  { id: 'd13', sede: 'Concepción', title: 'Charla: Situación actual de la anemia infecciosa equina', category: 'Charla', description: 'Felipe Riquelme, del SAG, presenta sobre la anemia infecciosa equina y nuevas normativas.', date: '2026-04-15', time: '11:00', location: 'Auditorio Dr. Alexis Lama, campus Las Tres Pascualas', faculty: 'Medicina Veterinaria', capacity: 90, requires_rsvp: true, tags: ['veterinaria'], status: 'published', image_url: '' },
  { id: 'd14', sede: 'Valdivia', title: 'Inauguración año académico de sede', category: 'Ceremonia', description: 'La Dra. Cecilia Morán dicta la charla magistral "Las mujeres en la universidad: desde 1877 a la actualidad".', date: '2026-04-15', time: '10:30', location: 'Aula magna, edificio E, sede Valdivia', faculty: 'Vicerrectoría Valdivia', capacity: 300, requires_rsvp: true, tags: ['académico'], status: 'published', image_url: '' },
  { id: 'd15', sede: 'Valdivia', title: 'Seminario "Invierte tu tiempo hoy, impacta mañana"', category: 'Seminario', description: 'Claves para emprender con Robinson Soto y Germán Ide. Organiza Ingeniería Comercial sede Valdivia.', date: '2026-04-14', time: '11:00', location: 'Aula Magna, sede Valdivia', faculty: 'Ingeniería Comercial', capacity: 120, requires_rsvp: true, tags: ['emprendimiento'], status: 'published', image_url: '' },
  { id: 'd16', sede: 'De la Patagonia', title: 'Inauguración Año Académico 2026', category: 'Ceremonia', description: 'Clase magistral "Virus y Pandemias: De humanos a salmones, una historia compartida", por el profesor Marcos Godoy.', date: '2026-04-14', time: '11:00', location: 'Aula Magna, sede De la Patagonia', faculty: 'Dirección de Comunicaciones', capacity: 250, requires_rsvp: true, tags: ['académico'], status: 'published', image_url: '' },
  { id: 'd17', sede: 'De la Patagonia', title: 'Operativo Odontológico Integral en Ayacara', category: 'Voluntariado', description: 'Voluntariado disciplinar clínico con atenciones de morbilidad. Organizan Odontología y VcM.', date: '2026-04-13', time: '08:30', location: 'Localidad de Ayacara, comuna de Chaitén', faculty: 'Odontología', capacity: null, requires_rsvp: false, tags: ['vcm', 'odontología'], status: 'published', image_url: '' },
  { id: 'd18', sede: 'Online', title: 'Charla "Guía Práctica de la Operación Renta 2026"', category: 'Charla', description: 'Paso a paso de la declaración de impuestos y deducciones. Organiza Ingeniería Comercial Advance.', date: '2026-04-15', time: '19:00', location: 'Online', faculty: 'Ingeniería Comercial Advance', capacity: 500, requires_rsvp: true, tags: ['online'], status: 'published', image_url: '' },
  { id: 'd19', sede: 'Online', title: 'Ejecuta tu propósito: ¡Emprende!', category: 'Charla', description: 'Charla de tendencia en alusión al día mundial del emprendimiento.', date: '2026-04-15', time: '19:00', location: 'Online', faculty: 'Dirección Gral. de Emprendimiento, Empleabilidad y Alumni', capacity: 500, requires_rsvp: true, tags: ['online', 'emprendimiento'], status: 'published', image_url: '' },
  { id: 'd20', sede: 'Santiago', title: 'Taller: Inteligencia Artificial en la educación superior', category: 'Taller', description: 'Borrador del taller para la próxima semana. Pendiente confirmar sala.', date: '2026-04-22', time: '15:00', location: 'Por confirmar, campus Los Leones', faculty: 'Dirección de Innovación Docente', capacity: 50, requires_rsvp: true, tags: ['ia', 'docencia'], status: 'draft', image_url: '' },
];

export const DEMO_REGISTRATIONS = [
  { id: 'r1', event_id: 'd2', full_name: 'Carolina Fuentes', email: 'carolina.fuentes@uss.cl', phone: '+56 9 8472 1103', rut: '18.234.567-9', user_type: 'estudiante', career: 'Ingeniería Comercial', campus: 'Santiago', comment: 'Traigo a una compañera', created_at: '2026-04-16T10:22:00' },
  { id: 'r2', event_id: 'd2', full_name: 'Martín Aguilera', email: 'maguilera@uss.cl', phone: '+56 9 5512 0988', rut: '16.009.223-K', user_type: 'funcionario', career: 'FENG', campus: 'Santiago', comment: '', created_at: '2026-04-16T11:05:00' },
  { id: 'r3', event_id: 'd5', full_name: 'Ignacia Vera', email: 'ivera@uss.cl', phone: '+56 9 9812 4455', rut: '20.114.882-3', user_type: 'estudiante', career: 'Ingeniería Comercial', campus: 'Santiago', comment: 'Presento mi idea', created_at: '2026-04-16T09:45:00' },
  { id: 'r4', event_id: 'd8', full_name: 'Rodrigo Pardo', email: 'rpardo@uss.cl', phone: '+56 9 6612 7811', rut: '15.445.901-2', user_type: 'estudiante', career: 'Enfermería', campus: 'Los Leones', comment: '', created_at: '2026-04-16T08:31:00' },
  { id: 'r5', event_id: 'd10', full_name: 'Valentina Soto', email: 'vsoto.e@uss.cl', phone: '+56 9 7844 1012', rut: '19.887.665-1', user_type: 'estudiante', career: 'Kinesiología', campus: 'Bellavista', comment: 'Corro la maratón', created_at: '2026-04-16T14:05:00' },
  { id: 'r6', event_id: 'd14', full_name: 'Paula Henríquez', email: 'phenriquez@uss.cl', phone: '+56 9 7022 8899', rut: '13.998.112-8', user_type: 'funcionario', career: 'Vicerrectoría', campus: 'Valdivia', comment: '', created_at: '2026-04-15T16:20:00' },
];
